CREATE TABLE users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name       VARCHAR(20),
    last_name        VARCHAR(30),
    password         VARCHAR(30),
    gender           CHAR,
    activated        BOOLEAN                                  NOT NULL,
    activation_token VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- onlly allow two genders F and M
ALTER TABLE users
ADD CONSTRAINT check_gender CHECK ( users.gender IN ('F', 'M') );
-------------------------------------------
--creating contact table + constraints
CREATE TABLE contact
(
    user_id      INTEGER     NOT NULL,
    email        VARCHAR(40) NOT NULL,
    phone_number VARCHAR(255),
    CONSTRAINT pk_contact PRIMARY KEY (user_id)
);

ALTER TABLE contact
    ADD CONSTRAINT uc_contact_email UNIQUE (email);

ALTER TABLE contact
    ADD CONSTRAINT FK_CONTACT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);