ALTER TABLE users
DROP
COLUMN activated;

ALTER TABLE users
DROP
COLUMN activation_token;

ALTER TABLE users
    ADD email_verified BOOLEAN;

UPDATE users
SET email_verified = false
WHERE email_verified IS NULL;

ALTER TABLE users
    ALTER COLUMN email_verified SET NOT NULL;

CREATE TABLE verification_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(200)                            NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id    INTEGER                                 NOT NULL,
    used       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_token_value ON verification_token (token);

CREATE INDEX idx_token_user ON verification_token (user_id);

ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATION_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE verification_token
    ADD CONSTRAINT uc_verification_token_token UNIQUE (token);